Repository jenkins-x/ext-spotbugs, pull requests merged in 2018-10, with the labels that each got.

#2 Jenkinsfile
  Jenkinsfile
Labels: approved, size/XS

#3 WIP dummy
  Jenkinsfile
Labels: do-not-merge/work-in-progress, size/L

#6 chore: improve readme
  README.md
Labels: approved, size/XS

#7 fix: add GitHub org
  Jenkinsfile
Labels: approved, size/XS

#10 Templates
  .stignore
  Gopkg.lock
  Gopkg.toml
  charts/ext-spotbugs/templates/deployment.yaml
  charts/ext-spotbugs/templates/role.yaml
  charts/ext-spotbugs/templates/rolebinding.yaml
  charts/ext-spotbugs/templates/serviceaccount.yaml
  main.go
  spotbugs_analyzer_install.sh
  spotbugs_analyzer_upgrade.sh
  vendor/github.com/jenkins-x/jx/pkg/apis/jenkins.io/v1/types_governance.go
  vendor/github.com/jenkins-x/jx/pkg/apis/jenkins.io/v1/types_pipeline.go
  vendor/github.com/jenkins-x/jx/pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
Labels: approved, size/L

#9 fix: better handling of facts
  .stignore
  Gopkg.lock
  Gopkg.toml
  charts/ext-spotbugs/templates/deployment.yaml
  charts/ext-spotbugs/templates/role.yaml
  charts/ext-spotbugs/templates/rolebinding.yaml
  charts/ext-spotbugs/templates/serviceaccount.yaml
  main.go
  vendor/github.com/jenkins-x/jx/pkg/apis/jenkins.io/v1/types_governance.go
  vendor/github.com/jenkins-x/jx/pkg/apis/jenkins.io/v1/types_pipeline.go
  vendor/github.com/jenkins-x/jx/pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
Labels: approved, size/L

#11 Update spotbugs_analyzer_install.sh
  spotbugs_analyzer_install.sh
Labels: approved, size/XS

#13 fix: use env var for name
  spotbugs_analyzer_install.sh
  spotbugs_analyzer_upgrade.sh
Labels: approved, size/XS

#14 fix: Ugh, missing v
  updatebot.sh
Labels: approved, size/XS

#15 fix: more repo refs wrong
  charts/ext-spotbugs/Makefile
  skaffold.yaml
Labels: approved, size/XS

#16 Fix: fix image name
  charts/ext-spotbugs/values.yaml
Labels: approved, size/XS

#17 fix: better readiness check
  main.go
Labels: approved, size/S

#21 fix: wrong fact
  main.go
Labels: approved, size/XS

#22 fix: not fatal
  main.go
Labels: approved, size/XS
